# Generated by Django 4.0.6 on 2022-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('translate', models.CharField(max_length=50)),
                ('word_example', models.TextField(max_length=300)),
            ],
        ),
    ]
