# Generated by Django 4.0.6 on 2022-07-17 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simple_dict', '0002_userserverword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserverword',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
